language: node_js

node_js:
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 0.10
  - 0.11

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
#notifications:
#  irc: "irc.freenode.org#travis"
